name: 's3-publish-action'
description: 'Publish repository to S3'
inputs:
  folder-name:  # id of input
    description: 'The folder to upload the repository to.'
    required: true
  bucket-name:  # id of input
    description: 'The name of the S3 bucket to upload the repository to.'
    required: true
  empty-folder:  # id of input
    description: 'Whether or not to empty the folder being published to prior to publishing. Must be one of "true", "false".'
    required: true
  exclusions:
    description: 'A comma separated list of glob patterns to exclude when uploading to S3.'
    required: false
    default: ".gitignore,.git/*"
outputs:
  s3-path:
    description: "The S3 path where the repository has been uploaded to."
    value: ${{ steps.set-output.outputs.s3-path }}
runs:
  using: "composite"
  steps:
    - id: run-script
      run: ${{ github.action_path }}/run.sh ${{ inputs.folder-name }} ${{ inputs.bucket-name }} ${{ inputs.empty-folder }} "${{ inputs.exclusions }}"
      shell: bash
    - id: set-output
      run: echo "::set-output name=s3-path::$(cat output)"
      shell: bash